CREATE TYPE user_role AS ENUM ('Admin', 'Distributor', 'Retailer', 'Driver');

CREATE TABLE users (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email VARCHAR(255) UNIQUE NOT NULL,
  role user_role DEFAULT 'Retailer',
  full_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku VARCHAR(50) UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  stock INT NOT NULL DEFAULT 0,
  price DECIMAL(12, 2) NOT NULL,
  status VARCHAR(50) DEFAULT 'In Stock',
  distributor_id UUID REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  company VARCHAR(255) NOT NULL,
  total_orders INT DEFAULT 0,
  total_spent DECIMAL(12, 2) DEFAULT 0,
  status VARCHAR(50) DEFAULT 'Active',
  distributor_id UUID REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id VARCHAR(50) UNIQUE NOT NULL,
  customer_name VARCHAR(255) NOT NULL,
  date DATE NOT NULL,
  total DECIMAL(12, 2) NOT NULL,
  status VARCHAR(50) DEFAULT 'Pending',
  distributor_id UUID REFERENCES users(id) ON DELETE CASCADE,
  retailer_id UUID REFERENCES users(id) ON DELETE SET NULL,
  driver_id UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- Helper function to check if user is Admin
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
  SELECT EXISTS (
    SELECT 1 FROM users WHERE id = auth.uid() AND role = 'Admin'
  );
$$ LANGUAGE sql SECURITY DEFINER;

-- Users policies
CREATE POLICY "Users can view own profile or Admin" ON users FOR SELECT USING (auth.uid() = id OR public.is_admin());
CREATE POLICY "Users can update own profile or Admin" ON users FOR UPDATE USING (auth.uid() = id OR public.is_admin());

-- Inventory policies
CREATE POLICY "Distributors or Admins can manage inventory" ON inventory FOR ALL USING (auth.uid() = distributor_id OR public.is_admin());
CREATE POLICY "Retailers can view all inventory" ON inventory FOR SELECT USING (EXISTS (SELECT 1 FROM users WHERE id = auth.uid() AND role IN ('Admin', 'Distributor', 'Retailer')));

-- Customers policies
CREATE POLICY "Distributors or Admins can manage customers" ON customers FOR ALL USING (auth.uid() = distributor_id OR public.is_admin());

-- Orders policies
CREATE POLICY "Distributors or Admins can manage orders" ON orders FOR ALL USING (auth.uid() = distributor_id OR public.is_admin());
CREATE POLICY "Retailers can manage their orders" ON orders FOR ALL USING (auth.uid() = retailer_id);
CREATE POLICY "Drivers can view assigned orders" ON orders FOR SELECT USING (auth.uid() = driver_id);
CREATE POLICY "Drivers can update assigned orders" ON orders FOR UPDATE USING (auth.uid() = driver_id);

-- Create a trigger to automatically create a profile in `users` when a new user signs up in `auth.users`
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, email, full_name, role)
  VALUES (new.id, new.email, COALESCE(new.raw_user_meta_data->>'full_name', 'New User'), COALESCE((new.raw_user_meta_data->>'role')::user_role, 'Retailer'));
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
